#!/usr/bin/env python
import gpxpy.geo
import clipboard
#import math
#from math import sin, cos, sqrt, atan2, radians

#import sys
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk


def newClipboardDetected(*args):
    global lastCoord
    coord = splitCoords(clip.wait_for_text())
    if coord is not False:
        print("New coordinate detected: " + str(coord))
        print("Last coordinate was: " + str(lastCoord))

        dist = calculate(lastCoord[0], lastCoord[1], coord[0], coord[1])
        print("Distance between coords is " + str(dist))

        lastCoord = coord


def splitCoords(text):
    try:
        coord = [float(x.strip()) for x in text.split(',')]
    except Exception as e:
        return False
    else:
        if not isinstance(coord[0], float) or not isinstance(coord[1], float):
            return False
        else:
            return coord


def calculate(lon1, lat1, lon2, lat2):
    dist = gpxpy.geo.haversine_distance(lat1, lon1, lat2, lon2)
    dist = dist / 1000
    dist = round(dist, 2)
    return dist


def cooldown(dist):
    time = " "

    if dist >= 1500:
        time = "120 minutes"

    elif dist >= 1403 and dist <= 1500:
        time = "120 minutes"

    elif dist >= 1344 and dist <= 1403:
        time = "119 minutes"

    elif dist >= 1300 and dist <= 1344:
        time = "117 minutes"

    elif dist >= 1221 and dist <= 1300:
        time = "112 minutes"

    elif dist >= 1180 and dist <= 1221:
        time = "109 minutes"

    elif dist >= 1020 and dist <= 1180:
        time = "101 minutes"

    elif dist >= 1007 and dist <= 1020:
        time = "97 minutes"

    elif dist >= 948 and dist <= 1007:
        time = "94 minutes"

    elif dist >= 897 and dist <= 948:
        time = "90 minutes"

    elif dist >= 839 and dist <= 897:
        time = "88 minutes"

    elif dist >= 802 and dist <= 839:
        time = "83 minutes"

    elif dist >= 751 and dist <= 802:
        time = "81 minutes"

    elif dist >= 700 and dist <= 751:
        time = "76 minutes"

    elif dist >= 650 and dist <= 700:
        time = "73 minutes"

    elif dist >= 600 and dist <= 650:
        time = "69 minutes"

    elif dist >= 550 and dist <= 600:
        time = "65 minutes"

    elif dist >= 500 and dist <= 550:
        time = "61 minutes"

    elif dist >= 450 and dist <= 500:
        time = "58 minutes"

    elif dist >= 400 and dist <= 450:
        time = "54 minutes"

    elif dist >= 350 and dist <= 400:
        time = "49 minutes"

    elif dist >= 328 and dist <= 350:
        time = "48 minutes"

    elif dist >= 300 and dist <= 328:
        time = "46 minutes"

    elif dist >= 250 and dist <= 300:
        time = "41 minutes"

    elif dist >= 201 and dist <= 250:
        time = "36 minutes"

    elif dist >= 175 and dist <= 201:
        time = "33 minutes"

    elif dist >= 150 and dist <= 175:
        time = "31 minutes"

    elif dist >= 125 and dist <= 150:
        time = "28 minutes"

    elif dist >= 100 and dist <= 125:
        time = "26 minutes"

    elif dist >= 90 and dist <= 100:
        time = "24 minutes"

    elif dist >= 80 and dist <= 90:
        time = "23 minutes"

    elif dist >= 70 and dist <= 80:
        time = "22 minutes"

    elif dist >= 60 and dist <= 70:
        time = "21 minutes"

    elif dist >= 50 and dist <= 60:
        time = "20 minutes"

    elif dist >= 45 and dist <= 50:
        time = "19 minutes"

    elif dist >= 40 and dist <= 45:
        time = "18 minutes"

    elif dist >= 35 and dist <= 40:
        time = "17 minutes"

    elif dist >= 30 and dist <= 35:
        time = "16 minutes"

    elif dist >= 25 and dist <= 30:
        time = "14 minutes"

    elif dist >= 20 and dist <= 25:
        time = "11 minutes"

    elif dist >= 15 and dist <= 20:
        time = "8 minutes"

    elif dist >= 10 and dist <= 15:
        time = "6 minutes"

    elif dist >= 8 and dist <= 10:
        time = "4 minutes"

    elif dist >= 5 and dist <= 8:
        time = "3 minutes"

    elif dist >= 4 and dist <= 5:
        time = "2 minutes"

    elif dist >= 3 and dist <= 4:
        time = "2 minutes"

    elif dist >= 2 and dist <= 3:
        time = "1 minutes"

    elif dist >= 1 and dist <= 2:
        time = "48 seconds"

    return time


# lat1 = float(var[0])
# long1 = float(var[1])

# lat2 = float(var[2])
# long2 = float(var[3])

#calc = calculate(37.802668, -122.4223910, 37.797440, -122.4031850)
# var1 = '37.802668,-122.4223910 '
# var2 = '32.878510,-117.237340'
# calc = calculate(37.802668,-122.4223910,32.878510,-117.237340)

# cooldown = cooldown(calc)
# print(calc, cooldown)




clip = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)
clip.connect('owner-change', newClipboardDetected)
Gtk.main()
